<h2 class="btn btn-block btn-danger col-sm-12">Sign-in</h2>
<?php
$postUrl = $this->url(array(
    'controller' => 'Register',
    'action' => 'forgetpassword'
        ));
?>
        <form role="form" method="post" action="<?php echo $postUrl; ?>" name="forget-password" id="forget-password">
    <?php if ($this->form->getMessages()) { ?>
        <div><ul>
                <?php
                $form_errors = $this->form->getMessages();
				
                foreach ($form_errors as $field => $arrErrors) {
                    echo '<li>' . $this->formErrors($arrErrors) . '</li>';
                }
                ?>
            </ul></div>
			
	<?php } ?>
	 <?php
    if ($this->error_message) {
        echo "<div class='error-msg'>" . $this->error_message . "</div>";
    }
    ?> <div class="site-section site-section-sm">
      <div class="container">
        <div class="row">
       
          <div class="col-md-12 col-lg-8 mb-5">
          
            
            

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="emailaddress">Email Address</label>
                 <?php echo $this->form->emailaddress; ?>
                </div>
              </div>
             


              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="phone">Mobile Number</label>
                  <?php echo $this->form->mobilenumber; ?>
                </div>
              </div>

            <div class="col-md-12 col-sm-12 text-center">
            <div class="form-group">
			<div align="left">
                <button type="submit" name="Submit" class="btn btn-default btn-warning text-center" id="sechemSearchButton">Forget Password ?</button>
            </div>
        </div>   
		</div>
                               
								
                            <div class="row form-group">
                           
                                         <a href="#">Reset Password ?</a>
                                    </div>
                        </div>
              	
            </div>
                </div>  
         			
            </form>
          
                           
                                   