<?php
$registration_details = $this->registration_details;
?>
<h2 class="btn btn-block btn-danger col-sm-12"> Register </h2>
<?php
$postUrl = $this->url(array(
    'controller' => 'Index',
    'action' => 'signin'
        ));
?>
        <form role="form" method="post" action="<?php echo $postUrl; ?>" name="sign-in" id="sign-in">
    <?php if ($this->form->getMessages()) { ?>
        <div><ul>
                <?php
                $form_errors = $this->form->getMessages();
				
                foreach ($form_errors as $field => $arrErrors) {
                    echo '<li>' . $this->formErrors($arrErrors) . '</li>';
                }
                ?>
            </ul></div>
			
	<?php } ?>
	 <?php
    if ($this->error_message) {
        echo "<div class='error-msg'>" . $this->error_message . "</div>";
    }
    ?>
                           
                                   <div class="row">
								    
	                               
									<div class="form-group col-sm-6 col-xs-12 role-item">
                                  <label>Email Address <sup class="require">*</sup> </label>
                                  <?php echo $this->form->emailaddress; ?>
                                   </div>
                                  							   
								  <div class="form-group col-sm-6 col-xs-12 role-item">
                                  <label>Password <sup class="require">*</sup> </label>
                                   <?php echo $this->form->password; ?>
                                    </div>	
										
                                         
                                         <div class="col-md-12 col-sm-12 text-center">
                                         <div class="form-group">
                           <button type="submit" name="Submit" class="btn btn-default btn-warning text-center" id="sechemSearchButton">Sign in</button>
                               </div>
                               </div>
							   
								
			                   	
							   <div class="checkbox">
                                        <label>
                                <input type="checkbox"> I agree to the terms of services and Privacy Policy
                            </label>
								
                            <div class="register-link m-t-15 text-center">
                                         <a href="#">Forget Password?</a></p>
                                    </div>
                        </div>
              	
            </div>
        
		</form>
		  	

		