<!-- Start carousel -->
 <div class="slide-one-item home-slider owl-carousel">
 <div class="site-blocks-cover overlay" style="background-image: url(images/pg1-1.jpg);" data-aos="fade" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-md-7 text-center" data-aos="fade">
              
              <h1 class="mb-2">Welcome To Paying Guest</h1>
              <h2 class="caption">Enjoy With Us</h2>
            </div>
          </div>
        </div>
      </div>  

      <div class="site-blocks-cover overlay" style="background-image: url(images/hero_3.jpg);" data-aos="fade" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-md-7 text-center" data-aos="fade">
              <h1 class="mb-2">Relaxing Room</h1>
              <h2 class="caption">Stay with Us</h2>
            </div>
          </div>
        </div>
      </div> 
	  </div>
	  <!-- End carousel -->
	  <!-- Start Main Contant box -->

    <div class="site-section bg-light">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto text-center mb-5 section-heading">
            <h2 class="mb-5"> Paying Guest Rooms Details</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="pg-room text-center">
              <a href="#" class="d-block mb-0 thumbnail"><img src="images/pg1-1.jpg" alt="Image" class="img-fluid"></a>
              <div class="pg-room-body">
                <h3 class="heading mb-0"><a href="#">Single Room</a></h3>
				<a href="#">Rent per month:Rs.10,000.00/-</a><br>
                <a href="#">Number of rooms:1</a><br>
				<a href="#">Location:Delhi</a>
               
				</div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="#" class="d-block mb-0 thumbnail"><img src="images/download (1).jpg" alt="Image" class="img-fluid"></a>
              <div class="pg-room-body">
                <h3 class="heading mb-0"><a href="#">Luxury Room</a></h3>
				<a href="#">Rent per month:Rs.20,000.00/-</a><br>
                <a href="#">Number of rooms:2</a><br>
				<a href="#">Location:Goa</a>
				
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="#" class="d-block mb-0 thumbnail"><img src="images/img_3.jpg" alt="Image" class="img-fluid"></a>
              <div class="pg-room-body">
                <h3 class="heading mb-0"><a href="#"> Standard Room</a></h3>
				<a href="#">Rent per month:Rs.8,000.00/-</a><br>
                <a href="#">Number of rooms:1</a><br>
				<a href="#">Location:Pune</a>
                
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="#" class="d-block mb-0 thumbnail"><img src="images/download.jpg" alt="Image" class="img-fluid"></a>
              <div class="pg-room-body">
                <h3 class="heading mb-0"><a href="#">Deluxe Room</a></h3>
				<a href="#">Rent per month:Rs.15,000.00/-</a><br>
                <a href="#">Number of rooms:2</a><br>
				<a href="#">Location:Mumbai</a>
               
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="#" class="d-block mb-0 thumbnail"><img src="images/images (1).jpg" alt="Image" class="img-fluid"></a>
              <div class="pg-room-body">
                <h3 class="heading mb-0"><a href="#">Ordinary Room</a></h3>
				<a href="#">Rent per month:Rs.5,000.00/-</a><br>
                <a href="#">Number of rooms:1</a><br>
				<a href="#">Location:Chennai</a>
              
              </div>
            </div>
          </div>
         
        </div>
      </div>
    </div>


    <div class="site-section">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6 mb-5 mb-md-0">
            
              <div class="img-border">
                
                  <img src="images/pg1-1.jpg" alt="" class="img-fluid">
                
              </div>

              <img src="images/download (1).jpg" alt="Image" class="img-fluid image-absolute">
            
          </div>
          <div class="col-md-5 ml-auto">
            

            <div class="section-heading text-left">
              <h2 class="mb-5">About Us</h2>
            </div>
            <p class="mb-4">Paying Guest Accomdation System is to provide user friendly environment to pg seker at affordable prices.</p>
            
          </div>
        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto text-center mb-5 section-heading">
            <h2 class="mb-5">Room Features</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <span class="flaticon-pool display-3 mb-3 d-block text-primary"></span>
              <h2 class="h5">Balcony</h2>
            </div>
          </div>
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <span class="flaticon-desk display-3 mb-3 d-block text-primary"></span>
              <h2 class="h5">Laundary</h2>
            </div>
          </div>
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <span class="flaticon-exit display-3 mb-3 d-block text-primary"></span>
              <h2 class="h5">Fire Exit</h2>
            </div>
          </div>
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <span class="flaticon-parking display-3 mb-3 d-block text-primary"></span>
              <h2 class="h5">Car Parking</h2>
            </div>
          </div>

          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <span class="flaticon-hair-dryer display-3 mb-3 d-block text-primary"></span>
              <h2 class="h5">Security</h2>
            </div>
          </div>

          
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="text-center p-4 item">
              <span class="flaticon-drink display-3 mb-3 d-block text-primary"></span>
              <h2 class="h5">Fully Air Conditioned</h2>
            </div>
          </div>
         </div>
      </div>
    </div>
    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto text-center mb-5 section-heading">
            <h2 class="mb-5">Gallery</h2>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-md-6 col-lg-3">
            <a href="images/pg1-1.jpg" class="image-popup img-opacity"><img src="images/pg1-1.jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="images/download (1).jpg" class="image-popup img-opacity"><img src="images/download (1).jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="images/img_3.jpg" class="image-popup img-opacity"><img src="images/img_3.jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="images/img_4.jpg" class="image-popup img-opacity"><img src="images/download.jpg" alt="Image" class="img-fluid"></a>
          </div>

          <div class="col-md-6 col-lg-3">
            <a href="images/img_4.jpg" class="image-popup img-opacity"><img src="images/images (1).jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="images/img_5.jpg" class="image-popup img-opacity"><img src="images/img_5.jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="images/img_6.jpg" class="image-popup img-opacity"><img src="images/img_6.jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="images/img_7.jpg" class="image-popup img-opacity"><img src="images/img_7.jpg" alt="Image" class="img-fluid"></a>
          </div>
		  </div>
      </div>
    </div>
    


   


        
    
    

  