<div class="cntnt">
    <ol class="breadcrumb  margin_top100">
  </ol>
   
	
	<center><div class="contact-us-img"><img src="<?php echo $this->baseUrl("imagesorg/index1.jpg"); ?>" alt="Contact Us" align="RIGHT"  ></div></center>
	       
<?php
$postUrl = $this->url(array(
    'controller' => 'Owner',
    'action' => 'registration'
        ));
?>
        <form role="form" method="post" action="<?php echo $postUrl; ?>" name="register-owner" id="register-owner">
    <?php if ($this->form->getMessages()) { ?>
        <div><ul>
                <?php
                $form_errors = $this->form->getMessages();
				
                foreach ($form_errors as $field => $arrErrors) {
                    echo '<li>' . $this->formErrors($arrErrors) . '</li>';
                }
                ?>
            </ul></div>
			
	<?php } ?>
	  <div class="site-section site-section-sm">
      <div class="container">
        <div class="row">
		<?php
    if ($this->errorMessage) {
        echo "<h4 class='alert-danger'>" . $this->errorMessage . "</h4>";
    }
    ?>
         <div class="col-md-12 col-lg-8 mb-5">
          <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
				<h3><center><label class="btn btn-block btn-info col-sm-12" for="name">REGISTER</label></h3>
                 <h3><center><label class="font-weight-bold" for="fullname">Name</label></h3>
                <h3><center><?php echo $this->form->name; ?></h3>
                </div>
              </div>
                 <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <h3><center><label class="font-weight-bold" for="phone">Contact Details</label></h3>
                  <h3><center><?php echo $this->form->contactno; ?></h3>
                </div>
              </div>
				<div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
				 <h3><center><label class="font-weight-bold" for="email">Email Address</label></h3>
                                 <h3><center><?php echo $this->form->emailaddress; ?></h3>
                 
               </div>
               </div>
                  <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
								 <h3><center><label class="font-weight-bold" for="password">Password</label></h3>
                                 <h3><center><?php echo $this->form->password; ?></h3>
                                </div>
                                </div>
                           <div class="row form-group">
                              <div class="col-md-12 mb-3 mb-md-0">
								<h3><center><label class="font-weight-bold" for="password">Repeat Password</label></h3>
								<h3><center><?php echo $this->form->repeatpassword; ?></h3>
                               </div>
                                </div>
              
			  <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <h3><center><label class="font-weight-bold" for="address">Address</label></h3>
                  <h3><center><?php echo $this->form->address; ?></h3>
                </div>
              </div>

             
				
				
								 <div class="checkbox">
                                  <h5><center><label>
                                <input type="checkbox">I agree to the terms of services and Privacy Policy
                            </label></h5>
             
			 <div class="col-md-12 col-sm-12 text-center">
            <div class="form-group">
			<div align="left">
                <h3><center><button type="submit" name="Submit" class="btn btn-default btn-warning text-center" id="sechemSearchButton">Register</button</h3>
            </div>
        </div>   
		</div>
                              
								
                            <h3><center><div class="row form-group">
                           <div class="col-md-12 mb-3 mb-md-0"> Already register?
                                         <a href="<?php echo $this->baseUrl('/owner/login'); ?>">Sign in</a>
                                    </div>
                        </div></h3>
              	
            </div>
                </div>  
         			
            </form>
          
                           
                                   