<?php
$customer_registrated_details = $this->customer_registrated_details;
//print_r($owner_registrated_details);
//die;
?>



	
		<div class="contact-us-img"><img src="<?php echo $this->baseUrl("imagesorg/authentication-vs-authorization.png"); ?>" alt="Contact Us" style="width:100%" ></div>
 <h2 class="btn btn-block btn-info col-sm-12 ">Registered Customer Details </h2>	
    <table class="table" style="width:100%" border="1">
        <tr>			

            <th scope="row">Name</th>
            <th scope="row">Mobile Number</th>
            <th scope="row">Email Address</th>
			<th scope="row">Gender</th>
			<th scope="row">Pg Name</th>
			<th scope="row">Address</th>
			
        </tr>
		<?php
		
        $i = 1;
	
 foreach ($customer_registrated_details as $value):
 
 { ?>
  <tr>
    <td><?php echo $value['username']; ?></td>
    <td><?php echo $value['contactno']; ?></td>
    <td><?php echo $value['email']; ?></td>
	<td><?php echo $value['gender']; ?></td>
    <td><?php echo $value['PG-Name'];?></td>
   <td><?php echo $value['address'];?></td>
	
	</tr>
  <?php
                $i++;
            }
        
        ?>  
		
<?php endforeach ?>

</table>
<p>&nbsp;&nbsp;</p>
</div>
