 
 <div class="site-section bg-light">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto text-center mb-5 section-heading">
            <h2 class="mb-5"> Paying Guest Rooms Details</h2>
          </div>
        </div>
		
        <div class="row">
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="pg-room text-center">
              <a href="<?php echo $this->baseUrl('Customer/divya-pghomedetail'); ?>" class="d-block mb-0 thumbnail"><img src="images/pg1-1.jpg" alt="Image" class="img-fluid"></a>
              <div class="pg-room-body">
                <h3 class="heading mb-0"><a href="<?php echo $this->baseUrl('Customer/divya-pghomedetail'); ?>">Divya PG Home</a></h3>
				<a href="<?php echo $this->baseUrl('Customer/divya-pghomedetail'); ?>">Rent per month:Rs.10,000.00/-</a><br>
                <a href="<?php echo $this->baseUrl('Customer/divya-pghomedetail'); ?>">Number of rooms:10</a><br>
				<a href="<?php echo $this->baseUrl('Customer/divya-pghomedetail'); ?>">Location:Delhi</a>
               
				</div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="<?php echo $this->baseUrl('Customer/nikhil-pghomedetail'); ?>" class="d-block mb-0 thumbnail"><img src="images/images (1).jpg" alt="Image" class="img-fluid"></a>
              <div class="pg-room-body">
                <h3 class="heading mb-0"><a href="<?php echo $this->baseUrl('Customer/nikhil-pghomedetail'); ?>">Nikhil PG Home</a></h3>
				<a href="<?php echo $this->baseUrl('Customer/nikhil-pghomedetail'); ?>">Rent per month:Rs.11,000.00/-</a><br>
                <a href="<?php echo $this->baseUrl('Customer/nikhil-pghomedetail'); ?>">Number of rooms:8</a><br>
				<a href="<?php echo $this->baseUrl('Customer/nikhil-pghomedetail'); ?>">Location:Goa</a>
				
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="<?php echo $this->baseUrl('Customer/kaushika-pghomedetail'); ?>" class="d-block mb-0 thumbnail"><img src="imagesorg/images.jpg" alt="Image" class="img-fluid"></a>
              <div class="pg-room-body">
                <h3 class="heading mb-0"><a href="<?php echo $this->baseUrl('Customer/kaushika-pghomedetail'); ?>">Kaushika PG Home</a></h3>
				<a href="<?php echo $this->baseUrl('Customer/kaushika-pghomedetail'); ?>">Rent per month:Rs.8,000.00/-</a><br>
                <a href="<?php echo $this->baseUrl('Customer/kaushika-pghomedetail'); ?>">Number of rooms:11</a><br>
				<a href="<?php echo $this->baseUrl('Customer/kaushika-pghomedetail'); ?>">Location:Pune</a>
                
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="<?php echo $this->baseUrl('Customer/shiva-pghomedetails'); ?>" class="d-block mb-0 thumbnail"><img src="imagesorg/images (2).jpg" alt="Image" class="img-fluid"></a>
              <div class="pg-room-body">
                <h3 class="heading mb-0"><a href="<?php echo $this->baseUrl('Customer/shiva-pghomedetails'); ?>">Shiva PG Home</a></h3>
				<a href="<?php echo $this->baseUrl('Customer/shiva-pghomedetails'); ?>">Rent per month:Rs.7,000.00/-</a><br>
                <a href="<?php echo $this->baseUrl('Customer/shiva-pghomedetails'); ?>">Number of rooms:9</a><br>
				<a href="<?php echo $this->baseUrl('Customer/shiva-pghomedetails'); ?>">Location:Mumbai</a>
               
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="<?php echo $this->baseUrl('Customer/daksh-pghomedetail'); ?>" class="d-block mb-0 thumbnail"><img src="imagesorg/images (3).jpg" alt="Image" class="img-fluid"></a>
              <div class="pg-room-body">
                <h3 class="heading mb-0"><a href="<?php echo $this->baseUrl('Customer/daksh-pghomedetail'); ?>">Daksh PG Home</a></h3>
				<a href="<?php echo $this->baseUrl('Customer/daksh-pghomedetail'); ?>">Rent per month:Rs.9,000.00/-</a><br>
                <a href="<?php echo $this->baseUrl('Customer/daksh-pghomedetail'); ?>">Number of rooms:8</a><br>
				<a href="<?php echo $this->baseUrl('Customer/daksh-pghomedetail'); ?>">Location:Chennai</a>
              
              </div>
            </div>
          </div>
         
        </div>
		<div class="col-md-12 col-sm-12 text-center">
            <div class="form-group">
			
			
			 <!--<a href="Register/register" class="btn btn-info" role="button">View Full PG Details</a>-->
			 <a href="Customer/viewdetails" class="btn btn-info" role="button">View  PG Information</a>
                 <!--<a href="Customer/check1-pgcustomerdetails" class="btn btn-info" role="button">View Full PG Details</a>-->
            </div>
			
        </div>
      </div>
    </div>
	
