  
  <?php
$aboutus_details = $this->aboutus_details;
?>
  <div class="site-section">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6 mb-5 mb-md-0">
            
              <div class="img-border">
                
                  <img src="images/pg1-1.jpg" alt="" class="img-fluid">
                
              </div>

              <img src="imagesorg/images (2).jpg" alt="Image" class="img-fluid image-absolute">
            
          </div>
          <div class="col-md-5 ml-auto">
            

            <div class="section-heading text-left">
              <h2 class="mb-5">About Us</h2>
            </div>
           <h5><b><p class="mb-4">Paying Guest Accomdation System is to provide user friendly environment to PG seeker at affordable prices.</p></b></h5>
            
          </div>
        </div>
      </div>
    </div>