<?php 
$captchanew = new Zend_Session_Namespace('captchanew');
$captchanew->captchanew = session_id();
$user = new Zend_Session_Namespace('user_session');
?>
<script type="text/javascript" nonce="<?php echo $user->nonce_str; ?>">
$(document).ready(function(){
	
        $('#user_name').focus();
		
		//document.getElementById("add_new_user").addEventListener("submit", validate_form);
  
	
	var user_role = $("#user_role").val();
	if(user_role == 2){
		$(".state-item").show();	
	}else{
		$(".state-item").hide();	
	}
	if(user_role == 6 || user_role == 4){
		$(".ministry-item").show();	
	}else{
		$(".ministry-item").hide();	
	}

	$("#user_role").change(function(){
		var user_role_val = $(this).val();		
		if(user_role_val == 2 || user_role_val == 2){
			$(".state-item").show();	
		}else{
			$(".state-item").hide();	
		}
		if(user_role_val == 6 || user_role_val == 4){
			$(".ministry-item").show();	
		}else{
			$(".ministry-item").hide();	
		}
	});	


jQuery("#add_new_user").submit(function ()
        {

	var iChars12 = "0123456789";
	var iChars = "!@#$%^&*()+=-[]_\\\';,./{}|\":<>?~`() ";
	
	var iChars_username = "!@#$%^&*()+=-[]\\\';,/{}|\":<>?~`() ";
	var iChars_allow_space = "!@#$%^&*()+=-[]_\\\';,./{}|\":<>?~`()";
	var name_regex = <?php echo TEXT_FIELD_VALIDATION; ?>
	
	var user_role = document.getElementById("user_role");
	var user_role_val = user_role.options[user_role.selectedIndex].value;

	if(user_role_val == 0){
		alert("Please select a role");
		document.addnewuser.user_role.focus();
		return false;
	}

	if(user_role_val == 2){
		if(document.addnewuser.state_name.value == '0' || document.addnewuser.state_name.value == null){
			alert("Please select a state");
			document.addnewuser.state_name.focus();
			return false;
		}
	}

	if(user_role_val == 6){
		if(document.addnewuser.ministry_name.value == '0' || document.addnewuser.ministry_name.value == null){
			alert("Please select a ministry");
			document.addnewuser.ministry_name.focus();
			return false;
		}
	}
	  	
	if(document.addnewuser.user_name.value == ''||document.addnewuser.user_name.value == null){
	   alert("Username field cannot be empty");
	   document.addnewuser.user_name.focus();
	   return false;
	}
  			    
	if(document.addnewuser.user_name.value != ''){
		for (var i = 0; i < document.addnewuser.user_name.value.length; i++) {
		if (iChars_username.indexOf(document.addnewuser.user_name.value.charAt(i)) != -1) {
		alert ("Username field has special characters. \nThese are not allowed.\n Please remove them and try again");
		document.addnewuser.user_name.focus();
		return false;
		}
	  }
	}
	if(document.addnewuser.user_name.value != ''){
		for (var i = 0; i < 1; i++) {
		if (iChars12.indexOf(document.addnewuser.user_name.value.charAt(i)) != -1) {
		alert ("Username field First character should be string");
		document.addnewuser.user_name.focus();
		return false;
		}
	  }
	}

	if(document.addnewuser.user_first_name.value == ''||document.addnewuser.user_first_name.value == null){
		alert("First name field cannot be empty");
		document.addnewuser.user_first_name.focus();
		return false;
	}
  			    
	if(document.addnewuser.user_first_name.value!=''){
		for (var i = 0; i < document.addnewuser.user_first_name.value.length; i++) {
		if (iChars_allow_space.indexOf(document.addnewuser.user_first_name.value.charAt(i)) != -1) {
		alert ("First Name field has special characters. \nThese are not allowed.\n Please remove them and try again.");
		document.addnewuser.user_first_name.focus();
		return false;
		}
	  }
	}

	if(document.addnewuser.user_first_name.value!=''){
		for (var i = 0; i < 1; i++) {
		if (iChars12.indexOf(document.addnewuser.user_first_name.value.charAt(i)) != -1) {
		alert ("First Name field First character should be string!");
		document.addnewuser.user_first_name.focus();
		return false;
		}
	  }  
	}
				
	if(document.addnewuser.user_last_name.value == ''||document.addnewuser.user_last_name.value == null){
		alert("Last Name field cannot be empty");
		document.addnewuser.user_last_name.focus();
		return false;
	}
  			    
	if(document.addnewuser.user_last_name.value != ''){
		for (var i = 0; i < document.addnewuser.user_last_name.value.length; i++) {
		if (iChars.indexOf(document.addnewuser.user_last_name.value.charAt(i)) != -1) {
		alert ("Last Name field has special characters. \nThese are not allowed.\n Please remove them and try again.");
		document.addnewuser.user_last_name.focus();
		return false;
		}
	  }
	}

	if(document.addnewuser.user_last_name.value!=''){
		for (var i = 0; i < 1; i++) {
			if (iChars12.indexOf(document.addnewuser.user_last_name.value.charAt(i)) != -1) {
				alert ("Last Name field First character should be string");
				document.addnewuser.user_last_name.focus();
				return false;
			}
		} 
	}
					
	if(document.addnewuser.user_designation.value != ''){
		if(!name_regex.test(jQuery("#user_designation").val())){
			alert ("Designation field has special characters. \nThese are not allowed.\n Please remove them and try again.");
			jQuery("#user_designation").focus();
			return false;
		}
	}

	if(document.addnewuser.user_email.value == '' || document.addnewuser.user_email.value == null){
		alert("E-mail Address field cannot be empty");
		document.addnewuser.user_email.focus();
		return false;
	}

	if(document.addnewuser.user_email.value != ''){
		var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,5})+$/;
		if (!filter.test(document.addnewuser.user_email.value)) {
			alert('Please provide a valid E-mail address');
			document.addnewuser.user_email.focus();
			return false;
		}
	}

	if(document.addnewuser.user_mobile.value == '' || document.addnewuser.user_mobile.value == null){
		alert("Mobile Number field cannot be empty");
		document.addnewuser.user_mobile.focus();
		return false;
	}
        
	if(document.addnewuser.user_mobile.value != ''){
		var pattern = /^[\s()+-]*([0-9][\s()+-]*){6,20}$/;
		if (!pattern.test(document.addnewuser.user_mobile.value) || document.addnewuser.user_mobile.value.length != 10) {
			alert("Please provide a valid Mobile Number");
			document.addnewuser.user_mobile.focus();
			return false;
		}
	}
	if(jQuery('#vercode').val() == ''){
		alert("Captcha code <?php echo CANTEMPTY; ?>");
		jQuery( "#vercode" ).focus();
		return false;
	} 
});
});
</script>
<h2 class="btn btn-block btn-danger margin_bottom10 col-sm-12">Add New User</h2>
	<?php 
	$postUrl = $this->url(array(
		'controller' => 'user',
		'action'  => 'add'
	));
	?>
	<form role="form" method="post" action="<?php echo $postUrl; ?>" name="addnewuser"  id="add_new_user" >
	<?php if($this->form->getMessages()){ ?>
		<div><ul>
		<?php 
		$form_errors = $this->form->getMessages();
		foreach($form_errors as $field => $arrErrors) {
			echo '<li>'.$this->formErrors($arrErrors).'</li>';
		}
		?>
		</ul></div>
	<?php } ?>
	<?php 
	if($this->error_message){
		echo "<div class='error-msg'>".$this->error_message."</div>"; 
	}
	?>
		<div class="row">
			<div class="form-group col-sm-6 col-xs-12 role-item">
				<label>Role<sup class="require">*</sup> </label>
				<?php echo $this->form->user_role; ?>
			</div>			
			<div class="form-group col-sm-6 col-xs-12 state-item">
				<label>State:</label>
				<?php echo $this->form->state_name; ?>
			</div>
			<div class="form-group col-sm-6 col-xs-12 ministry-item">
				<label>Ministry:</label>
				<?php echo $this->form->ministry_name; ?>
			</div>
		</div>
		<div class="row">		
			<!--<div class="form-group col-sm-12 col-xs-12 city-item">
				<label>District:</label>
				<?php //echo $this->form->cityname; ?>
			</div>-->
			<div class="form-group col-sm-6 col-xs-12">
				<label>Username<sup class="require">*</sup></label>
				<?php echo $this->form->user_name; ?>
			</div>
			<div class="form-group col-sm-6 col-xs-12">
				<label>First Name<sup class="require">*</sup></label>
				<?php echo $this->form->user_first_name;?>
			</div>
			<div class="form-group col-sm-6 col-xs-12">
				<label>Last Name<sup class="require">*</sup></label>
				<?php echo $this->form->user_last_name; ?>
			</div>
			<div class="form-group col-sm-6 col-xs-12">
				<label>Designation</label>
				<?php echo $this->form->user_designation; ?>
			</div>
			<div class="form-group col-sm-6 col-xs-12">
			  <label>E-mail Address<sup class="require">*</sup></label>
			  <?php echo $this->form->user_email;?>
			</div>
			<div class="form-group col-sm-6 col-xs-12">
				<label>Mobile Number<sup class="require">*</sup></label>
				<?php echo $this->form->user_mobile; ?>
			</div>
		</div>
		<div class="row">
			<!-----------Add Captcha Code Script----->
			<div class="form-group col-sm-4">
				<div><label>Captcha Code<sup class="require">*</sup></label></div>
				<img src="<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>" id="captcha" class="pull-left" width="248" height="40" />
				<a onclick="document.getElementById('captcha').src='<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>?'+Math.random();document.getElementById('vercode').focus();" id="change-image" class="menu4 refresh pull-left" style="cursor:pointer"><img src="<?php echo $this->baseUrl('images/refress.png'); ?>" class ="refresh" id="refresh" /></a>
				<?php echo $this->form->vercode; ?>
			   <input type="hidden"  name ="sessionCheck" value="<?php echo $captchanew->captchanew;?>" />
			</div>
		   <!--------------End Captcha Code------->
			<div class="col-md-12 col-sm-12 text-center">
				<div class="form-group">
					<input  type="submit" name="Submit" class="btn btn-default btn-warning text-center" id="sechemSearchButton">
					<button type="reset" name="Reset" class="btn active text-center" id="resetButton"><a href="<?php echo $this->baseUrl('user/add'); ?>"><?php echo CANCEL; ?></a></button>
				</div>
			</div>
		</div>
	</form>