<?php

 $userid = new Zend_Session_Namespace('userid');
        $admname = new Zend_Session_Namespace('adminMname');
	 $role = new Zend_Session_Namespace('role');
	// echo "ROLE=".$role->role;
	$captchanew = new Zend_Session_Namespace('captchanew');
	$captchanew->captchanew = session_id();
	$userinfodata = $this->userinfodata;
	?>

<script type="text/javascript" language="javascript">


/***************************************************/
// Mixing the password for login credintial
function mixUpValues(ecyn,keyt,keyt1)
{
	var stringis;
	stringis=ecyn.substr(0,12);
	stringis+=keyt;
	stringis+=ecyn.substr(12,10);
	stringis+=keyt1;
	stringis+=ecyn.substr(22);
	return stringis;
}

/*************************************************/
function valPwd2()
	{
		var iChars = "',\\\;&<>\"";
		var iChars1 = "',\\\;&<>\"~@#$%^*()_?><+_-|`:";
		var iChars_sec = "',\\\;&<>\"~@#$%^*()_><+_-|`:";
			/*********************************************************************************/
			if(document.frm_change.oldpassword.value=='' || document.frm_change.oldpassword.value == null)
			{
						alert("Old Password should not be blank.");
						document.frm_change.oldpassword.focus();
						return false;
						
			}
			if(document.frm_change.oldpassword.value!="")
				{
					//var encp=MD5(document.frm_change.oldpassword.value);
					//document.frm_change.oldpassword.value=mixUpValues(encp,document.frm_change.keyy.value,document.frm_change.keyy1.value);
					var hash = CryptoJS.HmacSHA256(document.frm_change.oldpassword.value, "");
					document.frm_change.oldpassword.value=mixUpValues(hash.toString(),document.frm_change.keyy.value,document.frm_change.keyy1.value);
			
			
				}


			if(document.frm_change.newpassword.value=='' || document.frm_change.newpassword.value== null)
			{
						alert("New Password should not be blank.");
						document.frm_change.newpassword.focus();
						return false;
						
			}

			
			 if(!(document.frm_change.newpassword.value.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/)))
					  {  
					 alert("Password should have atleast a lowercaseletter,Uppercaseletter,Numericnumber and Specialcharacter.");
					 document.frm_change.newpassword.focus();
					 return false;
											
					 }
			
		/*************************************************************************************/

		if(document.frm_change.newpassword.value!='')
			{
				if(document.frm_change.newpassword.value.length < 8)
					{
						alert("New Password should contain 8 characters.");
						document.frm_change.newpassword.focus();
						return false;
					}
					
					for (var i = 0; i < document.frm_change.newpassword.value.length; i++) {
						if (iChars.indexOf(document.frm_change.newpassword.value.charAt(i)) != -1) {
							alert ("New Password field is either empty or contains space or disallowed character ( \' \\\ < > & , ; \"  ). Please correct and try again.");
							document.frm_change.newpassword.focus();
							return false;
						}
				  }
			}
			if(document.frm_change.newpassword.value!="")
			{
				//var encp=MD5(document.frm_change.newpassword.value);
				//document.frm_change.newpassword.value=mixUpValues(encp,document.frm_change.keyy2.value,document.frm_change.keyy3.value);
				var hash = CryptoJS.HmacSHA256(document.frm_change.newpassword.value, "");
				document.frm_change.newpassword.value=mixUpValues(hash.toString(),document.frm_change.keyy2.value,document.frm_change.keyy3.value);
			}
			

		//if(!validatePassword(document.getElementById('new_pass').value, 'NOPARAM')) 
		//{
			//alert('The password does not meets the required criteria. See footnote for details');
			//return false;
		//}
			
			
			
			
			
			if(document.frm_change.conformnewpassword.value=='' || document.frm_change.conformnewpassword.value== null)
			{
						alert("Confirm Password should not be blank.");
						document.frm_change.conformnewpassword.focus();
						return false;
						
			}
		if(document.frm_change.conformnewpassword.value!='')
			{
				if(document.frm_change.conformnewpassword.value.length < 8)
					{
						alert("Confirm password should contain 8 characters.");
						document.frm_change.conformnewpassword.focus();
						return false;
					}
					

			}
			if(document.frm_change.conformnewpassword.value!="")
				{
					//var encp=MD5(document.frm_change.conformnewpassword.value);
					//document.frm_change.conformnewpassword.value=mixUpValues(encp,document.frm_change.keyy2.value,document.frm_change.keyy3.value);
					var hash = CryptoJS.HmacSHA256(document.frm_change.conformnewpassword.value, "");
					document.frm_change.conformnewpassword.value=mixUpValues(hash.toString(),document.frm_change.keyy2.value,document.frm_change.keyy3.value);
			
				}
			//password match
			if(document.frm_change.newpassword.value!='' && document.frm_change.newpassword.value!=''){
			//var com= StrComp(document.frm_change.new_pass.value , document.frm_change.new_pass.value)
				if(document.frm_change.newpassword.value != document.frm_change.conformnewpassword.value)
					{
						alert("New Password and Confirm password does not matched.");
						//document.frm_change.confirm_pass.focus();
						return false;
				
					}
	if(jQuery('#vercode').val() == '')
		{
			alert("Captcha code <?php echo CANTEMPTY; ?>");
			jQuery( "#vercode" ).focus();
			return false;
		} 
			
			}

			return true;		
	}
	

	
</script>

<script type="text/javascript" language="javascript">
jQuery(document).ready(function(){
	//SSO with dbthelpdesk
	<?php if(!empty($userinfodata)){ ?>
		var helpdeskurl = '<?php echo SSO_AJAX_PATH; ?>/change_password';
		var datastring = "name=<?php echo base64_encode($userinfodata['username']); ?>&lid=<?php echo base64_encode($userinfodata['id']); ?>&email=<?php echo base64_encode($userinfodata['email']); ?>&fname=<?php echo base64_encode($userinfodata['firstname']); ?>&lname=<?php echo base64_encode($userinfodata['lastname']); ?>";
		// alert(helpdeskurl);
		$.ajax({
			url : helpdeskurl,
			data : datastring,
			type : "POST",
			success:function(response){
				// alert(response);
			}
		});
		
	<?php } ?>
});
/* jQuery(document).ready(function(){
	jQuery("#frm_change").submit(function(){
		var string1 = removeSpacesnew(document.getElementById('mainCaptcha').value);
        var string2 = removeSpacesnew(document.getElementById('txtInput').value);
		<!-----------Add Captcha Code Script----->
		if (jQuery("#txtInput").val() == '')
		 {
			alert("<?php echo CAPTCHA_NOTEMPTY; ?>");
			jQuery( "#txtInput" ).focus();
			return false;
		 }
		if (string1!= string2){
		   alert("<?php echo CAPTCHA_INCORRECT; ?>");					  
		   return false;
         }
		 <!-----------Add Captcha Code Script----->
	});
function removeSpacesnew(string){
	return string.split(' ').join('');
}
}); */
</script>
	
<h2 class="btn btn-block btn-danger margin_bottom10 col-sm-12">Change Password</h2>
				
<?php
		$cmidata = $this->cmidata;
		$postUrlUpdate = $this->url(array('controller' => 'user','action'  => 'changeuserpassword'));
?>
			<form action="<?=$postUrlUpdate?>" method="post" name="frm_change" id="frm_change" onsubmit="return valPwd2();" class="changpass">
					<?php if($this->msg){?>
						<div class='error-msg'><span class="errors"><?php echo $this->escape($this->msg); ?></span></div>
					<?php }elseif($this->successMsg){
						echo "<div class='success-msg'>".$this->successMsg."</div>"; 
					}elseif($this->errorMessage){ ?>
						<div class='error-msg'><span class="errors"><?php echo $this->escape($this->errorMessage); ?></span></div>
					<?php } ?>

					<div class="row">
						<div class="form-group col-sm-12">
							<label>Old Password:<sup class="require">*</sup> </label>
							<?php echo $this->form->oldpassword?>
							<input name="keyy" type="hidden" class="textbox" id="keyy" size="37" value="<?php echo time(); ?>"/>
							<input name="keyy1" type="hidden" class="textbox" id="keyy1" size="37" value="<?php echo mt_rand(10000,99999); ?>"/>
						</div>
						<div class="form-group col-sm-12">
							<label>New Password:<sup class="require">*</sup> </label>
							<?php echo $this->form->newpassword?>
							<input name="keyy2" type="hidden" class="textbox" id="keyy2" size="37" value="<?php echo time(); ?>"/>
							<input name="keyy3" type="hidden" class="textbox" id="keyy3" size="37" value="<?php echo mt_rand(10000,99999); ?>"/>
						</div>
						<div class="form-group col-sm-12">
							<label>Confirm Password:<sup class="require">*</sup> </label>
							<?php echo $this->form->conformnewpassword?>
							
						</div>
							<!-----------Add Captcha Code Script----->
			 <div class="form-group col-sm-12">
				<label>Captcha Code<sup class="require">*</sup>  </label>
				<p>
					<img src="<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>" id="captcha" class="pull-left"/>
					<span><a  onclick="
						document.getElementById('captcha').src='<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>?'+Math.random();
						document.getElementById('vercode').focus();" id="change-image" class="menu4 refresh pull-left" style="cursor:pointer"><img src="<?php echo $this->baseUrl('images/refress.png'); ?>" class ="refresh" id="refresh" /></a>	</span>									
				</p>
				<p class="text-left">										
					<?php echo $this->form->vercode; ?>
				</p>
				<input type="hidden"  name ="sessionCheck" value="<?php echo $captchanew->captchanew;?>" />
            </div>
           <!--------------End Captcha Code------->
						<div class="form-group col-md-12 col-sm-12 text-center">
							<script type="text/javascript">
    document.write("<button type=\"submit\" name=\"Submit\" class=\"btn btn-default btn-warning text-center\" id=\"updateProfileButton\"  /> Change Password</button>");
                   </script>
                      <noscript>
                <p style="color: red;"><b><i>Please enable JavaScript to continue</i></b><p>
                   </noscript>
						</div>
					</div>
			</form>

