<?php 
$user = new Zend_Session_Namespace('user_session');
$captchanew = new Zend_Session_Namespace('captchanew');
$captchanew->captchanew = session_id();
?>

<script type="text/javascript" src="<?php echo $this->baseUrl('js/captcha.js') ?>" nonce="<?php echo $user->nonce_str; ?>"></script> 

<script type="text/javascript" language="javascript" nonce="<?php echo $user->nonce_str; ?>">
	jQuery(document).ready(function (){
		var iChars12 ="0123456789";
		var iChars = "!@#$%^&*()+=-[]_\\\';,./{}|\":<>?~`() ";
		var iChars1 = "!@#$%^&*()+=-[]_\\\';,./{}|\":<>?~`()";
		var iChars121 = "!#$%^&*()+=[]\\\';,/{}|\":<>?~`() ";
		var iChars_username = "!@#$%^&*()+=-[]\\\';,/{}|\":<>?~`() ";
		var iChars_allow_space = "!@#$%^&*()+=-[]_\\\';,./{}|\":<>?~`()";
		var name_regex = <?php echo TEXT_FIELD_VALIDATION; ?>;
		jQuery("#edituserform").submit(function () {
			if(document.edituserform.user_first_name.value == ''||document.edituserform.user_first_name.value == null){
				alert("First name field cannot be empty");
				document.addnewuser.user_first_name.focus();
				return false;
			}

			if(document.edituserform.user_first_name.value!=''){
				for (var i = 0; i < document.edituserform.user_first_name.value.length; i++) {
				if (iChars_allow_space.indexOf(document.edituserform.user_first_name.value.charAt(i)) != -1) {
				alert ("First Name field has special characters. \nThese are not allowed.\n Please remove them and try again.");
				document.edituserform.user_first_name.focus();
				return false;
				}
			  }
			}
			
			if(document.edituserform.user_first_name.value!=''){
				for (var i = 0; i < 1; i++) {
				if (iChars12.indexOf(document.edituserform.user_first_name.value.charAt(i)) != -1) {
				alert ("First Name field First character should be string!");
				document.edituserform.user_first_name.focus();
				return false;
				}
			  }  
			}

			if(document.edituserform.user_last_name.value == ''||document.edituserform.user_last_name.value == null){
				alert("Last Name field cannot be empty");
				document.edituserform.user_last_name.focus();
				return false;
			}
						
			if(document.edituserform.user_last_name.value != ''){
				for (var i = 0; i < document.edituserform.user_last_name.value.length; i++) {
				if (iChars.indexOf(document.edituserform.user_last_name.value.charAt(i)) != -1) {
				alert ("Last Name field has special characters. \nThese are not allowed.\n Please remove them and try again.");
				document.edituserform.user_last_name.focus();
				return false;
				}
			  }
			}

			if(document.edituserform.user_last_name.value!=''){
				for (var i = 0; i < 1; i++) {
					if (iChars12.indexOf(document.edituserform.user_last_name.value.charAt(i)) != -1) {
						alert ("Last Name field First character should be string");
						document.edituserform.user_last_name.focus();
						return false;
					}
				} 
			}
					
			if(document.edituserform.user_designation.value != ''){
				if(!name_regex.test(jQuery("#user_designation").val())){
					alert ("Designation field has special characters. \nThese are not allowed.\n Please remove them and try again.");
					jQuery("#user_designation").focus();
					return false;
				}
			}

			if(document.edituserform.user_email.value == '' || document.edituserform.user_email.value == null){
				alert("E-mail Address field cannot be empty");
				document.edituserform.user_email.focus();
				return false;
			}

			if(document.edituserform.user_email.value != ''){
				var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,5})+$/;
				if (!filter.test(document.edituserform.user_email.value)) {
					alert('Please provide a valid E-mail address');
					document.edituserform.user_email.focus();
					return false;
				}
			}

			if(document.edituserform.user_mobile.value == '' || document.edituserform.user_mobile.value == null){
				alert("Mobile Number field cannot be empty");
				document.edituserform.user_mobile.focus();
				return false;
			}
				
			if(document.edituserform.user_mobile.value != ''){
				var pattern = /^[\s()+-]*([0-9][\s()+-]*){6,20}$/;
				if (!pattern.test(document.edituserform.user_mobile.value)) {
					alert("Please provide a valid Mobile Number");
					document.edituserform.user_mobile.focus();
					return false;
				}
			}
			
			if(jQuery('#vercode').val() == ''){
				alert("Captcha code <?php echo CANTEMPTY; ?>");
				jQuery( "#vercode" ).focus();
				return false;
			}
			return true;
	
		});
	});

</script>

<h2 class="btn btn-block btn-danger margin_bottom10 col-sm-12">Edit User</h2>				

<form role="form" method="post" action="<?php //echo $postUrlUpdate; ?>" name="edituserform" id="edituserform" >
	<?php 
		if($this->error_message){
			echo "<div class='error-msg'>".$this->error_message."</div>"; 
		}
	?>
    <?php if ($this->form->getMessages()) { ?>
        <div><ul>
                <?php
                $form_errors = $this->form->getMessages();
                foreach ($form_errors as $field => $arrErrors) {
                    echo '<li>' . $this->formErrors($arrErrors) . '</li>';
                }
                ?>
            </ul></div>
    <?php } ?>
	<div class="row">
		<div class="form-group col-sm-6 col-xs-12">
			<label>First Name<sup class="require">*</sup></label>
			<?php echo $this->form->user_first_name;?>
		</div>
		<div class="form-group col-sm-6 col-xs-12">
			<label>Last Name<sup class="require">*</sup></label>
			<?php echo $this->form->user_last_name; ?>
		</div>
		<div class="form-group col-sm-6 col-xs-12">
			<label>Designation</label>
			<?php echo $this->form->user_designation; ?>
		</div>
		<div class="form-group col-sm-6 col-xs-12">
		  <label>E-mail Address<sup class="require">*</sup></label>
		  <?php echo $this->form->user_email;?>
		</div>
		<div class="form-group col-sm-6 col-xs-12">
			<label>Mobile Number<sup class="require">*</sup></label>
			<?php echo $this->form->user_mobile; ?>
		</div>
	</div>
			
	<div class="row">
		<!-----------Add Captcha Code Script----->
		<div class="form-group col-sm-4">
			<div><label>Captcha Code<sup class="require">*</sup></label></div>
			<img src="<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>" id="captcha" class="pull-left" width="248" height="40" />
			<a onclick="document.getElementById('captcha').src='<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>?'+Math.random();document.getElementById('vercode').focus();" id="change-image" class="menu4 refresh pull-left" style="cursor:pointer"><img src="<?php echo $this->baseUrl('images/refress.png'); ?>" class ="refresh" id="refresh" /></a>
			<?php echo $this->form->vercode; ?>
		   <input type="hidden"  name ="sessionCheck" value="<?php echo $captchanew->captchanew;?>" />
		</div>
	   <!--------------End Captcha Code------->
		<div class="col-md-12 col-sm-12 text-center">
			<div class="form-group">
				<button type="submit" name="Submit" class="btn btn-default btn-warning text-center" id="sechemSearchButton">Submit</button>
				<button type="reset" name="Reset" class="btn active text-center" id="resetButton" onclick="goCancel();"><?php echo CANCEL; ?></button>
			</div>
		</div>
	</div>
</form>