<?php
$edit_profile_url = $this->url(array('controller' => 'user', 'action' => 'edit-user-profile')); 
$change_password_url = $this->url(array('controller' => 'user','action' => 'change-user-password'));
$user_info = $this->user_info;
?>

<h2 class="btn btn-block btn-danger margin_bottom10 col-sm-12">My Account</h2>	

<div class="cntnt">
	<div class="row">
		<div class="col-sm-12">
			<?php 
				if($this->success_message){
					echo "<div class='success-msg'>".$this->success_message."</div>"; 
				}
			?>
			<div id="profilePage">
				<div id="profile">
					<div align="left">
						<ul class="menu_1g">
							<li><a href="<?php echo $edit_profile_url;?>" class="menu1 btn btn-default btn-warning text-center rolBtn">Edit Profile</a></li>
							<li><a href="<?php echo $change_password_url;?>" class="menu1 btn btn-default btn-warning text-center rolBtn">Change Password</a></li>
						</ul>
					</div>
					<div id="info">
					<p><span class="ttl">Role:</span><span class="dtl"><?php if($user_info['user_role']) echo $user_info['user_role']; ?></span></p>		
					<p><span class="ttl">Username:</span><span class="dtl"><?php if($user_info['user_name']) echo $user_info['user_name']; ?></span></p>
					<p><span class="ttl">Name:</span><span class="dtl"><?php if($user_info['user_first_name']) echo ucfirst($user_info['user_first_name'])." ".ucfirst($user_info['user_last_name']); ?></span></p>
					<p><span class="ttl">Designation:</span><span class="dtl"><?php if($user_info['user_designation']) echo $user_info['user_designation']; ?></span></p>
					<p><span class="ttl">Mobile No. :</span><span class="dtl"><?php if($user_info['user_mobile']) echo $user_info['user_mobile']; ?></span></p>
					<p><span class="ttl">Email Id:</span><span class="dtl"><?php if($user_info['user_email']) echo $user_info['user_email']; ?></span></p>
					</div>
					<div class="clr"></div>
				</div>
			</div>		
		</div>
	</div>
</div>
