<?php
$captchanew = new Zend_Session_Namespace('captchanew');
$captchanew->captchanew = session_id();
$user = new Zend_Session_Namespace('user_session');
?>

<h2 class="btn btn-block btn-danger col-sm-12">Manage Users</h2>

<div class="cntnt">
    <?php if ($this->success_message) { ?>	
        <div class="success-msg margin_top20"> <?php echo $this->success_message; ?></div>
    <?php } ?>
    <?php if ($this->error_message) { ?>	
        <div class="success-msg margin_top20"> <?php echo $this->error_message; ?></div>
    <?php } ?>	
    <?php
    $user_list = $this->user_list;
    $user_count = $this->user_count;

    $postUrl = $this->url(array('controller' => 'user', 'action' => 'user-inactive'));
    ?>

    <!-- search form -->
    <!--<form class="form-inline" role="form" method="get">			
            <div class="col-md-6 col-sm-12">
                    <div class="form-group margin-left-15">
                     <label><?php //echo SEARCH_BY;   ?></label><input type="search" class="light-table-filter form-control" data-table="order-table" placeholder="User Name,Full Name,Email">
                    </div>
            </div>
    </form>-->
    <!-- end---->

    <div class="col-md-12 col-sm-12 text-right margin_bottom10">
        <a class="btn btn-warning" href="<?php echo $this->baseUrl('user/add'); ?>" title="Add New User">Add New User</a>
        <a class="btn btn-warning margin-right-15" href="<?php echo $this->baseUrl('user/assign-scheme-user-list'); ?>" title="Add New User">Assign Scheme</a>
    </div>

    <!--<div class="col-sm-12 col-md-12 text-center record_box">
    <?php //echo $user_count . " User(s) Found"; ?>
    </div>-->
    <div class="margin_top10">
        <form class="form-inline webform-client-form" role="form" accept-charset="UTF-8" method="post" action="<?php echo $postUrl; ?>" id="user_form">   
            <table class="table table-striped table-bordered" id="user_table">					 
                <thead>
                    <tr>
                        <th>#</th> 
                        <th>SNo.</th>
                        <th>User name</th>
                        <th>Full Name</th>
                        <th>Mobile Number</th>
                        <th>Email Id</th>
                        <th>Status</th>
                        <th>Role</th>
                        <th>Edit</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($user_count == 0) { ?>
                        <tr>
                            <td colspan="10" align="center" bgcolor="#FFFFFF" class="alert"><?php echo RECORD_EMPTY; ?></td>
                        </tr>
                    <?php } else { ?>
                        <?php
                        $inc = 1;
                        foreach ($user_list as $key => $val) {
                            ?>
                            <tr>
                                <td><input type="checkbox" name="user_id[<?php echo $val['user_id']; ?>]"></td>
                                <td><?php echo $inc + $this->start; ?></td>
                                <td><?php echo $this->escape($val['user_name']); ?></td>
                                <td><?php echo $this->escape($val['user_first_name']) . " " . $this->escape($val['user_last_name']); ?></td>
                                <td><?php echo $this->escape($val['user_mobile']); ?></td>
                                <td><?php echo $this->escape($val['user_email']); ?></td>
                                <td><?php echo ($this->escape($val['user_status'] == 1)) ? "Active" : "Inactive"; ?></td>
                                <td><?php echo $this->escape($val['role_name']); ?></td>
                                <?php
                                $edit_url = $this->url(array(
                                            'controller' => 'user',
                                            'action' => 'edit-user'
                                        )) . "?id=" . base64_encode($this->escape($val['user_id']));
                                ?>
                                <td><a href="<?php echo $edit_url; ?>" class="menu1">Edit</a></td>
                            </tr>
                            <?php
                            ++$inc;
                        }
                    }
                    ?>
                </tbody>
            </table>
            <div class="status">
                <select class="form-control" name="user_status" id="statusId">
                    <option value="1">Active</option>
                    <option value="0">Inactive</option>
                </select>
                <input type="hidden" name ="sessionCheck" value="<?php echo $captchanew->captchanew; ?>" />
                <button class="btn btn-default btn-warning text-center rolBtn" type="Submit" name="Submit">Submit</button>
            </div>
        </form>
    </div>	
</div>
<script src="<?php echo $this->baseUrl('js/jquery.dataTables.min.js'); ?>" nonce="<?php echo $user->nonce_str; ?>"></script>
<link rel="STYLESHEET" type="text/css" href="<?php echo $this->baseUrl('css/jquery.dataTables.min.css'); ?>">
<script nonce="<?php echo $user->nonce_str; ?>">

    $(document).ready(function () {

        // Atleast One checkbox should be selected.	
        $("#user_form").submit(function () {
            var checked = $("#user_form input:checked").length > 0;
            if (!checked) {
                alert("<?php echo SELECT_USERS_ACTIVATE_DEACTIVATE; ?>");
                return false;
            }
        });

        //$('#myTable').DataTable();

        $('#user_table').DataTable({
            "lengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
            'processing': true,
            'serverSide': false,
            'columnDefs': [{
                    'targets': [1, 4, 6, 7, 8],
                    'orderable': false
                }],
            "pageLength": 20,
            "dom": '<"left"if>rt<"bottom"pl><"clear">'
        });

        $('#user_form #user_table_filter input').addClass('light-table-filter form-control');
        $('#user_form select').addClass('form-control');
    });

</script>
