<?php
$customerpg_details = $this-> customerpg_details;
$showhome1_details = $this-> showhome1_details;
$showhome2_details = $this-> showhome2_details;
$showhome3_details = $this-> showhome3_details;
$showhome4_details = $this-> showhome4_details;
//print_r($customerhome_details);
//die;
?> 
<?php
$postUrl = $this->url(array(
    'controller' => 'Admin',
    'action' => 'pg-homedetails'
        ));
?>
<form role="form" method="post" action="<?php echo $postUrl; ?>" name="add-contactus" id="add-contactus">
<div class="cntnt">
    <ol class="breadcrumb  margin_top100">
	</ol>
 <h2 class="btn btn-block btn-info col-sm-12 "> PG Home Details</h2>
 <div class="pg-img"><img src="<?php echo $this->baseUrl("imagesorg/images (21).jpg"); ?>" alt="Chennai-image" align="left" ></div>
	  <div class="pg-img"><img src="<?php echo $this->baseUrl("imagesorg/images (23).jpg"); ?>" alt="Chennai-image" align="left" ></div>
		<div class="pg-img"><img src="<?php echo $this->baseUrl("imagesorg/images (1).jpg"); ?>" alt="Chennai-image" align="left" ></div>
<div class="pg-img"><img src="<?php echo $this->baseUrl("imagesorg/index.jpg"); ?>" alt="Chennai-image" align="left" ></div>
<div class="pg-img"><img src="<?php echo $this->baseUrl("imagesorg/images (14).jpg"); ?>" alt="Chennai-image" align="left" ></div>

	<table style="width:100%" border="1">
	 
        <tr>			

            <th scope="row">Name</th>
            <th scope="row">Location</th>
            <th scope="row">Rent Per Month</th>
			<th scope="row">No.of Rooms</th>
			<th scope="row">Address</th>
			 <th  scope="row">Balcony Facility</th>
                <th scope="row">Electricity Facility</th>
                <th scope="row">CarParking Facility</th>
                <th scope="row">Security Facility</th>
				<th scope="row">Fire Exit Facility</th>
				<th scope="row">Fully Air Conditioned Facility</th>
        </tr>
		<?php
		
        $i = 1;
	
 foreach ($customerpg_details as $entry):
 
 { ?>
  <tr>
    <td><?php echo $entry['name']; ?></td>
    <td><?php echo $entry['location']; ?></td>
    <td><?php echo $entry['rent']; ?></td>
    <td><?php echo $entry['rooms'];?></td>
	<td><?php echo $entry['address'];?></td>
	 <td><?php echo $entry['balcony']; ?></td>
    <td><?php echo $entry['electricity']; ?></td>
    <td><?php echo $entry['carparking']; ?></td>
    <td><?php echo $entry['security'];?></td>
	<td><?php echo $entry['fireexit'];?></td>
	<td><?php echo $entry['ac'];?></td>
	</tr>
  <?php
                $i++;
            }
        
        ?>  
		
<?php endforeach ?>
<?php
		
        $i = 1;
	
 foreach ($showhome1_details as $entry):
 
 { ?>
  <tr>
    <td><?php echo $entry['pghome_name']; ?></td>
    <td><?php echo $entry['location']; ?></td>
    <td><?php echo $entry['rent']; ?></td>
    <td><?php echo $entry['numberofrooms'];?></td>
	<td><?php echo $entry['address'];?></td>
	 <td><?php echo $entry['balcony']; ?></td>
    <td><?php echo $entry['electricity']; ?></td>
    <td><?php echo $entry['parking']; ?></td>
    <td><?php echo $entry['security'];?></td>
	<td><?php echo $entry['fireexit'];?></td>
	<td><?php echo $entry['AC'];?></td>
	</tr>
  <?php
                $i++;
            }
        
        ?>  
		
<?php endforeach ?>
<?php
		
        $i = 1;
	
 foreach ($showhome2_details as $entry):
 
 { ?>
  <tr>
    <td><?php echo $entry['pg_name']; ?></td>
    <td><?php echo $entry['pg_location']; ?></td>
    <td><?php echo $entry['pg_rent']; ?></td>
    <td><?php echo $entry['pg_rooms'];?></td>
	<td><?php echo $entry['pg_address'];?></td>
	 <td><?php echo $entry['balcony']; ?></td>
    <td><?php echo $entry['electricity']; ?></td>
    <td><?php echo $entry['parking_area']; ?></td>
    <td><?php echo $entry['security'];?></td>
	<td><?php echo $entry['fireexit'];?></td>
	<td><?php echo $entry['Airconditioned'];?></td>
	</tr>
  <?php
                $i++;
            }
        
        ?>  
		
<?php endforeach ?>
		<?php
		
        $i = 1;
	
 foreach ($showhome3_details as $entry):
 
 { ?>
  <tr>
    <td><?php echo $entry['name']; ?></td>
    <td><?php echo $entry['home_location']; ?></td>
    <td><?php echo $entry['rentpermonth']; ?></td>
    <td><?php echo $entry['rooms'];?></td>
	<td><?php echo $entry['address'];?></td>
	 <td><?php echo $entry['balcony_facility']; ?></td>
    <td><?php echo $entry['electricity_facility']; ?></td>
    <td><?php echo $entry['parking_facility']; ?></td>
    <td><?php echo $entry['security'];?></td>
	<td><?php echo $entry['fireexit'];?></td>
	<td><?php echo $entry['fullyac'];?></td>
	</tr>
  <?php
                $i++;
            }
        
        ?>  
		
<?php endforeach ?>
	<?php
		
        $i = 1;
	
 foreach ($showhome4_details as $entry):
 
 { ?>
  <tr>
    <td><?php echo $entry['name']; ?></td>
    <td><?php echo $entry['location']; ?></td>
    <td><?php echo $entry['permonthrent']; ?></td>
    <td><?php echo $entry['rooms'];?></td>
	<td><?php echo $entry['pghome_address'];?></td>
	
	 <td><?php echo $entry['balcony_facility']; ?></td>
    <td><?php echo $entry['electricity_facility']; ?></td>
    <td><?php echo $entry['parking_facility']; ?></td>
    <td><?php echo $entry['security'];?></td>
	<td><?php echo $entry['fireexit'];?></td>
	<td><?php echo $entry['ac_facility'];?></td>
	</tr>
  <?php
                $i++;
            }
        
        ?>  
		
<?php endforeach ?>
</table>

 
        

         
			

   
               
            </div>
			
        </div>
		</form>
		
		