<header class="container-fluid">
<div class="site-wrap">

    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->
    <div class="site-navbar-wrap js-site-navbar bg-white">
      <div class="container">
        <div class="site-navbar bg-light">
          <div class="py-1">
            <div class="row align-items-center">
              <div class="col-2">
                <h2 class="mb-0 site-logo"><a href="index.html">Paying Guest</a></h2>
              </div>
              <div class="col-10">
                <nav class="site-navigation text-right" role="navigation">
                  <div class="container">
                    
                    <div class="d-inline-block d-lg-none  ml-md-0 mr-auto py-3"><a href="#" class="site-menu-toggle js-menu-toggle"><span class="icon-menu h3"></span></a></div>
                    <ul class="site-menu js-clone-nav d-none d-lg-block">
                      <li class="active">
                        <a href="/payingguest/">Home</a>
                      </li>
					  <li class="divider">|</li>
                     
                       <li> <a href="/Payingguest/Customer">Customer</a>
                        
                          </li>
						  <li class="divider">|</li>

                      </li>
                      <li><a href="/Payingguest/Owner/registration">Owner</a></li>
					  
					  <li class="divider">|</li>
                      <li><a href="/Payingguest/Register/register">Register/Signup</a></li>
					  <li class="divider">|</li>
                      <li><a href="/Payingguest/Aboutus">About Us</a></li>
					  <li class="divider">|</li>
					  <li><a href="/Payingguest/Contactus">Contact Us</a></li>
					  
					   
					
					  
					  
					  
                    </ul>
                  </div>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
	</header>
  
