<?php
$captchanew = new Zend_Session_Namespace('captchanew');
$captchanew->captchanew = session_id();
$user = new Zend_Session_Namespace('user_session');
?>

<script type="text/javascript" language="javascript" nonce="<?php echo $user->nonce_str; ?>">
//Encrypting password
function mixUpValues(ecyn,key1,key2){
	var string_val;
	string_val = ecyn.substr(0,12);
	string_val += key1;
	string_val += ecyn.substr(12,10);
	string_val += key2;
	string_val += ecyn.substr(22);
	return string_val;
}

function validate_form(){
	var iChars = "',\\\;&<>\"";
	var iChars1 = "',\\\;&<>\"~@#$%^*()_?><+_-|`:";
	var iChars_sec = "',\\\;&<>\"~@#$%^*()_><+_-|`:";

	if(document.frm_change.old_password.value=='' || document.frm_change.old_password.value == null){
		alert("Old Password cannot be empty");
		document.frm_change.old_password.focus();
		return false;
	}

	if(document.frm_change.new_password.value == '' || document.frm_change.new_password.value == null){
		alert("New Password cannot be empty");
		document.frm_change.new_password.focus();
		return false;
	}

	if(document.frm_change.new_password.value != '' || document.frm_change.new_password.value != null){
		var passwordval = document.frm_change.new_password.value;
		if(/^(?=.*\d)(?=.*[@#\-_$%^&+=ยง!\?])(?=.*[a-z])(?=.*[A-Z])[0-9A-Za-z@#\-_$%^&+=ยง!\?]{8,20}$/.test(passwordval) == false){
		alert("Your password quality is too bad. Please use some special character,Numbers,Upper case Letter and Lower case letter");
		   document.frm_change.new_password.focus();
		   return false;
		}
	}
		
	if(document.frm_change.new_password.value != ''){
		if(document.frm_change.new_password.value.length < 8){
			alert("New Password should contain minimum 8 characters");
			document.frm_change.new_password.focus();
			return false;
		}
					
		for (var i = 0; i < document.frm_change.new_password.value.length; i++) {
			if (iChars.indexOf(document.frm_change.new_password.value.charAt(i)) != -1) {
				alert ("New Password field is either empty or contains space or disallowed character ( \' \\\ < > & , ; \"  ). Please correct and try again");
				document.frm_change.new_password.focus();
				return false;
			}
		}
	}

	if(document.frm_change.confirm_new_password.value == '' || document.frm_change.confirm_new_password.value == null){
		alert("Confirm Password cannot be empty");
		document.frm_change.confirm_new_password.focus();
		return false;
	}

	if(document.frm_change.confirm_new_password.value!=''){
		if(document.frm_change.confirm_new_password.value.length < 8){
			alert("Confirm password should contain minimu 8 characters");
			document.frm_change.confirm_new_password.focus();
			return false;
		}
	}

	//password match
	if(document.frm_change.newpassword.value != '' && document.frm_change.newpassword.value != ''){
		if(document.frm_change.newpassword.value != document.frm_change.confirm_new_password.value){
			alert("New Password and Confirm password does not match");
			return false;
		}
		if(jQuery('#vercode').val() == ''){
			alert("Captcha code cannot be empty");
			jQuery( "#vercode" ).focus();
			return false;
		} 
	}
	
	if(document.frm_change.old_password.value != ""){
		var hash = CryptoJS.HmacSHA256(document.frm_change.old_password.value, "");
		document.frm_change.old_password.value = mixUpValues(hash.toString(),document.frm_change.keyy.value,document.frm_change.keyy1.value);
	}
	
	if(document.frm_change.new_password.value != ""){
		var hash = CryptoJS.HmacSHA256(document.frm_change.new_password.value, "");
		document.frm_change.new_password.value = mixUpValues(hash.toString(),document.frm_change.encode_val1.value,document.frm_change.encode_val.value);
	}

	if(document.frm_change.confirm_new_password.value != ""){
		var hash = CryptoJS.HmacSHA256(document.frm_change.confirm_new_password.value, "");
		document.frm_change.confirm_new_password.value = mixUpValues(hash.toString(),document.frm_change.encode_val1.value,document.frm_change.encode_val.value);
	}


	return true;		
}

$(document).ready(function(){
	document.getElementById("frm_change").addEventListener("submit", validate_form);
});
</script>
	
<h2 class="btn btn-block btn-danger margin_bottom10 text-center col-sm-12">Change Password</h2>
				
<form action="" method="post" name="frm_change" id="frm_change" class="changpass">
	<?php if($this->success_message){ ?>
		<div class='success-msg'><?php echo $this->escape($this->success_message); ?></div> 
	<?php }
		if($this->error_message){ ?>
		<div class='error-msg'><span class="errors"><?php echo $this->escape($this->error_message); ?></span></div>
	<?php } ?>
	<div class="col-sm-4">
	</div>
	<div class="col-sm-8">
		<div class="form-group col-sm-12">
			<div class="col-sm-2">
				<label>Old Password:<sup class="require">*</sup> </label>
			</div>
			<div class="col-sm-6">
				<?php echo $this->form->old_password; ?>
				<input name="keyy" type="hidden" class="textbox" id="keyy" size="37" value="<?php echo time(); ?>"/>
				<input name="keyy1" type="hidden" class="textbox" id="keyy1" size="37" value="<?php echo mt_rand(10000,99999); ?>"/>
			</div>
		</div>
		<div class="form-group col-sm-12">
			<div class="col-sm-2">
				<label>New Password:<sup class="require">*</sup> </label>
			</div>
			<div class="col-sm-6">
				<?php echo $this->form->new_password; ?>
				<input name="encode_val1" type="hidden" class="textbox" id="encode_val1" size="37" value="<?php echo time(); ?>"/>
				<input name="encode_val" type="hidden" class="textbox" id="encode_val" size="37" value="<?php echo mt_rand(10000,99999); ?>"/>
			</div>
		</div>
		<div class="form-group col-sm-12">
			<div class="col-sm-2">
				<label>Confirm Password:<sup class="require">*</sup> </label>
			</div>
			<div class="col-sm-6">
				<?php echo $this->form->confirm_new_password; ?>
			</div>
		</div>

	<div class="form-group col-sm-12">
		<div class="col-sm-2">
			<label>Captcha Code<sup class="require">*</sup> </label>
		</div>
		<div class="col-sm-6">
			<p>
				<img src="<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>" id="captcha" class="pull-left" width="248" height="40" />
				<a onclick="document.getElementById('captcha').src='<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>?'+Math.random();document.getElementById('vercode').focus();" id="change-image" class="menu4 refresh pull-left" style="cursor:pointer"><img src="<?php echo $this->baseUrl('images/refress.png'); ?>" class ="refresh" id="refresh" /></a>
			</p>
			<p class="text-left">										
				<?php echo $this->form->vercode; ?>
			</p>
		</div>
		<div class="form-group col-sm-12">
			<div class="col-sm-2"></div>
			<div class="col-sm-6">
				<input type="hidden"  name ="sessionCheck" value="<?php echo $captchanew->captchanew;?>" />
			</div>
		</div>
		<div class="form-group col-md-12 col-sm-12">
			<div class="col-sm-2"></div>
			<div class="col-sm-6">
				<button type="submit" name="Submit" class="btn btn-default btn-warning text-center" id="updateProfileButton">Change Password</button>
			</div>
		</div>
	</div>
	</div>
</form>