<?php $user = new Zend_Session_Namespace('user_session'); ?>
<script type="text/javascript" language="javascript" nonce="<?php echo $user->nonce_str; ?>">
	jQuery(document).ready(function () {
		jQuery("#login-form").submit(function () {
			if(document.frm_login.user_name.value == ''||document.frm_login.user_name.value == null){
				alert("Username field cannot be empty");
				document.frm_login.user_name.focus();
				return false;
			}
			if(document.frm_login.vercode.value == ''||document.frm_login.vercode.value == null){
				alert("Captcha code cannot be empty");
				document.frm_login.vercode.focus();
				return false;
			}
			return true;
		});

    });
</script>
		
<?php
$captchanew = new Zend_Session_Namespace('captchanew');
$captchanew->captchanew = session_id();
?>

<!--Start Main Contant box-->
<section class="container-fluid mainContant" id="mainContant">
	<section class="login height-400">
		<div class="container login-sec">
			<div class="col-md-12 col-sm-12 margin-bottom-10">
				<section class="login_sec">
					<?php
					if($this->success_message){?>
						<div class="success-msg margin_top20"> <?php echo $this->escape($this->success_message); ?></div>
					<?php }else if($this->error_message){ ?>
						<div class="error-msg margin_top20"><?php echo $this->escape($this->error_message);?></div>
					<?php } ?>

					<?php $postUrl = $this->url(array('controller' => 'authnew', 'action'  => 'forgot-password')); ?>
					<form id="login-form" name="frm_login" method="post" action="<?=$postUrl?>">
						<div class="form">
							<h2>Forgot Password</h2>
							<p>
								<span class="fontawesome-user"><span class=" icon user"></span></span>
								<?php echo $this->form->user_name; ?>
							</p>
							<p>
								<img src="<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>" id="captcha" class="pull-left" width="248" height="40" />
								<a onclick="document.getElementById('captcha').src='<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>?'+Math.random();document.getElementById('vercode').focus();" id="change-image" class="menu4 refresh pull-left" style="cursor:pointer"><img src="<?php echo $this->baseUrl('images/refress.png'); ?>" class ="refresh" id="refresh" /></a>
							</p>
							<p class="text-left">
								<?php echo $this->form->vercode; ?>
							</p>
							<input type="hidden"  name ="sessionCheck" value="<?php echo $captchanew->captchanew;?>" />
							<p>   
								<input id="Submit1" type="submit" value="E-mail new password" name="submit" />
							</p>
                        </div>
					</form>    
				</section>
				<div class="clear"></div>
			</div>
		</div>
	</section>	
</section>