<?php 
$captchanew = new Zend_Session_Namespace('captchanew');
$captchanew->captchanew = session_id();
$user = new Zend_Session_Namespace('user_session');
?>

<script type="text/javascript" language="javascript" nonce="<?php echo $user->nonce_str; ?>">

//Encrypting password
function mixUpValues(ecyn,key1,key2){
	var string_val;
	string_val = ecyn.substr(0,12);
	string_val += key1;
	string_val += ecyn.substr(12,10);
	string_val += key2;
	string_val += ecyn.substr(22);
	return string_val;
}

	jQuery(document).ready(function () {
		jQuery("#login-form").submit(function () {
			if(document.frm_change.new_password.value == ''||document.frm_change.new_password.value == null){
				alert("New Password field cannot be empty");
				document.frm_change.new_password.focus();
				return false;
			}

			if(document.frm_change.new_password.value.length < 8){
				alert("New Password field will take minimum 8 characters");
				document.frm_change.new_password.focus();
				return false;
			}

			if(!(document.frm_change.new_password.value.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/))){  
				 alert("Password should have atleast a lowercaseletter,Uppercaseletter,Numericnumber and Specialcharacter.");
				 document.frm_change.new_password.focus();
				 return false;
			}

			if(document.frm_change.confirm_new_password.value == ''||document.frm_change.confirm_new_password.value == null){
				alert("Confirm Password field cannot be empty");
				document.frm_change.confirm_new_password.focus();
				return false;
			}

			if(document.frm_change.confirm_new_password.value.length < 8){
				alert("Confirm Password field will take minimum 8 characters!");
				document.frm_change.confirm_new_password.focus();
				return false;
			}

			if(document.frm_change.new_password.value != document.frm_change.confirm_new_password.value){
				alert("New Password and Confirm password does not match");
				document.frm_change.new_password.focus();
				return false;
			}
			/*if(document.frm_change.vercode.value == ''||document.frm_change.vercode.value == null){
				alert("Captcha code cannot be empty");
				document.frm_change.vercode.focus();
				return false;
			}*/
			
			if(document.frm_change.new_password.value != ""){
				var hash = CryptoJS.HmacSHA256(document.frm_change.new_password.value, "");
				document.frm_change.new_password.value = mixUpValues(hash.toString(),document.frm_change.encode_val.value,document.frm_change.encode_val1.value);
			}
			
			if(document.frm_change.confirm_new_password.value != ""){
				var hash = CryptoJS.HmacSHA256(document.frm_change.confirm_new_password.value, "");
				document.frm_change.confirm_new_password.value = mixUpValues(hash.toString(),document.frm_change.encode_val.value,document.frm_change.encode_val1.value);
			}		
			
			if(jQuery('#vercode').val() == ''){
				alert("Captcha code cannot be empty");
				jQuery( "#vercode" ).focus();
				return false;
			} 
		
			return true;
		});

    });
</script>

<!--Start Main Contant box-->
<section class="container-fluid mainContant" id="mainContant">
	<section class="login height-400">
		<div class="container login-sec">
			<div class="col-md-12 col-sm-12 margin-bottom-10">
			
				<section class="login_sec">
					<?php if($this->success_message){ ?>
						<div class="success-msg margin_top20"><?php echo $this->escape($this->success_message); ?></div>
					<?php }
						if($this->error_message){ ?>
						<div class='error-msg margin_top20'><span class="errors"><?php echo $this->escape($this->error_message); ?></span></div>
					<?php } ?>				
					<form action="<?php //echo $postUrlUpdate;?>" method="post" name="frm_change" id="login-form" class="webform-client-form">				
                        <div class="form">
                            <h2>Reset Password</h2>
                            <p>
								<span class="fontawesome-user"><span class=" icon user"></span></span>
                              	<?php echo $this->form->new_password; ?>
								<input name="encode_val" type="hidden" class="textbox" id="encode_val" size="37" value="<?php echo time(); ?>"/>
								<input name="encode_val1" type="hidden" class="textbox" id="encode_val1" size="37" value="<?php echo mt_rand(10000,99999); ?>"/>								
                            </p>
							<p>
								<span class="fontawesome-user"><span class=" icon user"></span></span>
								<?php echo $this->form->confirm_new_password; ?>
							</p>
							<?php echo $this->form->token; ?>
							<p>
								<img src="<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>" id="captcha" class="pull-left" width="248" height="40" />
								<a onclick="document.getElementById('captcha').src='<?php echo $this->baseUrl('cool_capcha/captcha.php'); ?>?'+Math.random();document.getElementById('vercode').focus();" id="change-image" class="menu4 refresh pull-left" style="cursor:pointer"><img src="<?php echo $this->baseUrl('images/refress.png'); ?>" class ="refresh" id="refresh" /></a>
							</p>
							<p class="text-left">
								<?php echo $this->form->vercode; ?>
							</p>
								<input type="hidden"  name ="sessionCheck" value="<?php echo $captchanew->captchanew;?>" />
                            <p>
                                <input id="Submit1" type="submit" value="Reset Password" name="submit" />
                            </p>
                        </div>
					</form>    
				</section>
				<div class="clear"></div>
			</div>
		</div>
	</section>	
</section>